### PR TITLE
new dashboard

### PR DESCRIPTION
**Pull request by duck-rh**
Old Bitergia dashboards are no longer available, so using a direct link
to the full Bitergia dashboard.
Used a plain simple page as we don't need any specific generation
anymore.
Also add missing communities also having a Bitergia dashboard.

### CODE REVIEW

**Comment by duck-rh** [comment]
@bproffitt could you have a look please?

**Comment by duck-rh** [comment]
@jasonbrooks maybe? (bkp seems busy)

**Comment by jasonbrooks** [comment]
Duck, we just migrated the community site to WordPress. I'll take a look at
how to present this on the new site.

**Comment by duck-rh** [comment]
was fast :-).
You have the Bitergia links to all communities in the patch.
Once this is all over I'll cleanup the remaining bits on the Ansible side of things.

**Comment by duck-rh** [comment]
abandoned as the site moved to WP

**Pull request closed without merging**
