### PR TITLE
Added 053118 blog

### PR DESCRIPTION
**Pull request by bproffitt**

### CODE REVIEW

**Comment by bproffitt** [comment]
@duck-rh @mscherer @jasonbrooks The CI checks are failing and I don't know why. The error seems to be throwing when the "bundle exec middleman build --verbose" is being run, but the raw logs don't tell me more than that--possible something to do with favicon? (https://api.travis-ci.org/v3/job/386136572/log.txt)

I have not been running middleman locally for weeks, because no matter how many times I install gems, they refuse to be recognized, so I can't help you there.

**Comment by duck-rh** [comment]
It's not obvious. I am trying some tests.

**Comment by duck-rh** [comment]
Well, it's eluding me.
I thought it was the tags, as I've run into bugs when using tags containing spaces, but I see this site has used them for quite some time.
I wondered if it was not related to the events too because my tests show it is not related to this specific PR, but all event files validate well.
@bproffitt  this was to say I did not forget you, but no solution yet.

**Comment by duck-rh** [comment]
Not sure why the Gemfile.lock is not sufficient here, but the Kramdown pinning @mscherer made for RDO is working well (ported in #148).

**Pull request merged**
